<?php

namespace itoldyooBundle\Entity\Repository;

use itoldyooBundle\Entity\User;
use itoldyooBundle\Entity\UserEmail;
use Doctrine\ORM\EntityRepository;
 
/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function createUser(User $user){

		$em = $this->getDoctrine()->getManager();
		$em->getConnection()->beginTransaction(); // suspend auto-commit
		try {
		    $em->persist($user);
		    $em->flush();
		    $em->getConnection()->commit();
		} catch (Exception $e) {
		    $em->getConnection()->rollback();
		    throw $e;
		}

	}

}